ciudadanos_usuarios = []
ciudadanos_usuarios_nombres = []
ciudadanos_usuarios_claves = []
ciudadanos_bloqueados_usuarios = []
ciudadanos_a_bloquear = []
administradores_usuarios = []
eventos = []
sensores = []
